name: keepapp
description: A new Flutter application.

version: 1.0.2+2

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  rxdart: ^0.27.3
  flutter_colorpicker: ^1.0.3
  fluttertoast: ^8.0.8
  tinycolor: ^1.0.3
  linear_gradient: ^0.1.12
  url_launcher: ^6.0.19
  flutter_staggered_grid_view: ^0.6.1
  flutter_swiper: ^1.1.6
  provider: ^6.0.2
  intl: ^0.17.0
  overlay_support: ^1.2.1
  flutter_svg: ^1.0.3
  cross_local_storage: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Blaster
      fonts:
        - asset: assets/fonts/Blaster.ttf